version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # HTTP server
      - "2345:2345" # Debugging port
    volumes:
      - .:/app
      - /app/tmp
    environment:
      - AIR_DEBUG=true
